# Display.
title: "Still Magic"
subtitle: "How to Build Research Software You Can Trust and Still Be Home in Time for Dinner"
author: "Greg Wilson"
copyrightyear: "2019"
repo: "https://github.com/merely-useful/still-magic"
website: "https://merely-useful.github.io/still-magic/"
email: "gvwilson@third-bit.com"
organization: https://github.com/merely-useful/
isbn: "000-0-0000000-0-0"

# Order for table of contents.
toc:
  lessons:
  - /intro/
  - /automate/
  - /interlude-01/
  - /configure/
  - /unit/
  - /verify/
  - /logging/
  - /ghp/
  - /workflow/
  - /process/
  - /integrate/
  - /tools/
  - /style/
  - /refactor/
  - /structure/
  - /inclusive/
  - /package/
  - /publish/
  - /docs/
  - /teamwork/
  - /pacing/
  - /finale/
  bib:
  - /bib/
  extras:
  - /license/
  - /conduct/
  - /citation/
  - /contributing/
  - /gloss/
  - /objectives/
  - /keypoints/
  - /design/

# Tell Jekyll that "en" is a collection (whose files are found in "_en").  This
# is what allows us to loop over files in various inclusions.  We use "en" to
# indicate English, and can use other two-letter codes for other languages.
collections:
  en:
    output: true

# Specify the use of the "lesson" template for elements of the "en" collection.
defaults:
  - scope:
      path: ""
      type: en
    values:
      language: "en"
      layout: "lesson"

# Translations keyed by language.  This lookup table allows us to put the right
# titles on inclusion blocks in various languages.
translations:
  en:
    generated: "Last generated"
    questions: "Questions"
    keypoints: "Key Points"
    singlepage: "Single page version"

# Standard Jekyll settings.
repository: <USERNAME>/<PROJECT>
highlighter: rouge
plugins:
- "jekyll-redirect-from"
exclude:
- BUILD.md
- CITATION.md
- CONDUCT.md
- LICENSE.md
- Makefile
- README.md
- bin
- node_modules
- tex
