# Display.
title: "Still Magic"
subtitle: "How to Put Research Software Into Production and Still Be Home in Time for Dinner"
editor: "Greg Wilson"
copyrightyear: "2019"
repo: "https://github.com/merely-useful/still-magic"
website: "https://merely-useful.github.io/still-magic/"
email: "gvwilson@third-bit.com"
organization: https://github.com/merely-useful/
isbn: "000-0-0000000-0-0"
disclaimer: true

# Order for table of contents.
toc:
  lessons:
  - intro
  - automate
  - syndicate
  - configure
  - logging
  - unit
  - verify
  - branches
  - backlog
  - style
  - process
  - integrate
  - remote
  - tools
  - docs
  - refactor
  - project
  - inclusive
  - package
  - publish
  - teamwork
  - pacing
  - finale
  bib:
  - bib
  extras:
  - license
  - conduct
  - citation
  - contributing
  - gloss
  - objectives
  - keypoints
  - rules
